/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import * as THREE from "three";
import React, { useRef } from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";
import { useFrame } from "@react-three/fiber";

type GLTFResult = GLTF & {
  nodes: {
    Leaf001: THREE.Mesh;
    Tree001: THREE.Mesh;
    Floating_Roots: THREE.Mesh;
    Frame: THREE.Mesh;
    Icosphere003: THREE.Mesh;
    Icosphere003_1: THREE.Mesh;
    Icosphere004: THREE.Mesh;
    Icosphere004_1: THREE.Mesh;
    Portal: THREE.Mesh;
    PortalStair1: THREE.Mesh;
    PortalStair2: THREE.Mesh;
    Icosphere: THREE.Mesh;
    Icosphere_1: THREE.Mesh;
    Icosphere001: THREE.Mesh;
    Icosphere001_1: THREE.Mesh;
    Tunnel: THREE.Mesh;
    Torus: THREE.Mesh;
    Torus001: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    Cylinder003_1: THREE.Mesh;
    Cylinder004: THREE.Mesh;
    Cylinder004_1: THREE.Mesh;
    Cylinder005: THREE.Mesh;
    Cylinder005_1: THREE.Mesh;
    Cylinder006: THREE.Mesh;
    Cylinder006_1: THREE.Mesh;
    Cylinder007: THREE.Mesh;
    Cylinder007_1: THREE.Mesh;
    Cylinder008: THREE.Mesh;
    Cylinder008_1: THREE.Mesh;
    Cylinder009: THREE.Mesh;
    Cylinder009_1: THREE.Mesh;
    Cylinder010: THREE.Mesh;
    Cylinder010_1: THREE.Mesh;
    Cylinder011: THREE.Mesh;
    Cylinder011_1: THREE.Mesh;
    Crystal: THREE.Mesh;
    Crystal001: THREE.Mesh;
    Crystal002: THREE.Mesh;
    Crystal003: THREE.Mesh;
    Crystal004: THREE.Mesh;
    Crystal005: THREE.Mesh;
    Crystal006: THREE.Mesh;
    Crystal007: THREE.Mesh;
    Crystal008: THREE.Mesh;
    Crystal009: THREE.Mesh;
    Crystal010: THREE.Mesh;
    Crystal011: THREE.Mesh;
    Crystal012: THREE.Mesh;
    Crystal013: THREE.Mesh;
    Crystal014: THREE.Mesh;
    Crystal015: THREE.Mesh;
    Crystal016: THREE.Mesh;
  };
  materials: {
    ["Material.005"]: THREE.MeshStandardMaterial;
    ["Bark.001"]: THREE.MeshStandardMaterial;
    ["Soil.002"]: THREE.MeshStandardMaterial;
    ["Material.001"]: THREE.MeshStandardMaterial;
    Rock: THREE.MeshPhysicalMaterial;
    Water: THREE.MeshPhysicalMaterial;
    Soil: THREE.MeshPhysicalMaterial;
    ["Material.002"]: THREE.MeshStandardMaterial;
    ["Material.003"]: THREE.MeshStandardMaterial;
    Bark: THREE.MeshStandardMaterial;
    ["Material.004"]: THREE.MeshStandardMaterial;
    Grass: THREE.LineBasicMaterial;
    ["Fence Wood"]: THREE.MeshStandardMaterial;
    ["Fence Top"]: THREE.MeshStandardMaterial;
    Crystal: THREE.MeshStandardMaterial;
  };
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF("/assets/model.glb") as GLTFResult;

  const torus1 = useRef<THREE.Mesh>(null!);
  const torus2 = useRef<THREE.Mesh>(null!);

  useFrame((state) => {
    torus1.current.rotation.y += 0.00125;
    torus2.current.rotation.y += 0.0025;
  });

  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Floating_Roots.geometry}
        material={materials["Soil.002"]}
        position={[3.507, 1.701, -1.224]}
        rotation={[-Math.PI, 0.031, -Math.PI]}
        scale={0.078}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Frame.geometry}
        material={materials["Material.001"]}
        position={[3.896, 1.856, -1.195]}
        rotation={[Math.PI, -1.105, Math.PI]}
        scale={[0.017, 0.014, 0.017]}
      />
      <group
        position={[3.524, 1.861, -2.443]}
        rotation={[Math.PI, -1.105, Math.PI]}
        scale={[0.203, 0.155, 0.203]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003.geometry}
          material={materials.Rock}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere003_1.geometry}
          material={materials.Water}
        />
      </group>
      <group
        position={[4.191, 2.072, -0.292]}
        rotation={[Math.PI, -1.105, Math.PI]}
        scale={0.198}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004.geometry}
          material={materials.Rock}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere004_1.geometry}
          material={materials.Soil}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Portal.geometry}
        material={nodes.Portal.material}
        position={[3.842, 2.133, -1.069]}
        rotation={[Math.PI, -1.105, Math.PI]}
        scale={[0.092, 0.078, 0.078]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortalStair1.geometry}
        material={materials["Material.002"]}
        position={[3.835, 1.854, -1.074]}
        rotation={[Math.PI, -1.105, Math.PI]}
        scale={[0.222, 0.027, 0.119]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.PortalStair2.geometry}
        material={materials["Material.003"]}
        position={[3.835, 1.827, -1.074]}
        rotation={[0, 1.105, 0]}
        scale={[-0.266, -0.02, -0.142]}
      />
      <group
        position={[0.006, 0.001, 0]}
        rotation={[0, -1.136, 0]}
        scale={[0.288, 0.832, 0.288]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere.geometry}
          material={materials.Rock}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Icosphere_1.geometry}
          material={materials.Soil}
        />
      </group>
      <group
        position={[4.053, 3.002, -1.441]}
        rotation={[-Math.PI, 0.353, -Math.PI]}
        scale={0.153}
      >
        <mesh
          name="Icosphere001"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001.geometry}
          material={materials.Bark}
          morphTargetDictionary={nodes.Icosphere001.morphTargetDictionary}
          morphTargetInfluences={nodes.Icosphere001.morphTargetInfluences}
        />
        <mesh
          name="Icosphere001_1"
          castShadow
          receiveShadow
          geometry={nodes.Icosphere001_1.geometry}
          material={materials["Material.004"]}
          morphTargetDictionary={nodes.Icosphere001_1.morphTargetDictionary}
          morphTargetInfluences={nodes.Icosphere001_1.morphTargetInfluences}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus.geometry}
        material={nodes.Torus.material}
        rotation={[-0.058, 0.045, -0.123]}
        scale={[4.576, 4.069, 4.576]}
        ref={torus1}
      >
        <meshStandardMaterial wireframe color={'#aaf'}/>
      </mesh>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Torus001.geometry}
        material={nodes.Torus001.material}
        position={[0.228, -2, 0]}
        rotation={[0.035, 0.039, 0.081]}
        scale={[3.733, 3.32, 3.733]}
        ref={torus2}
      >
        <meshStandardMaterial wireframe color={'#aaf'}/>
      </mesh>
      <lineSegments
        geometry={nodes.Grass.geometry}
        castShadow
        receiveShadow
      >
        <meshStandardMaterial color={'#663377'} transparent opacity={0.85} /> 
      </lineSegments>
      <group
        position={[1.659, 1.939, -2.591]}
        rotation={[3.136, 0.24, -3.061]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder003_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[-0.314, 1.829, -2.953]}
        rotation={[-3.141, 0.047, 3.085]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder004_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[0.675, 1.925, -2.828]}
        rotation={[0.006, -0.219, 0.084]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder005_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[2.652, 1.934, -2.286]}
        rotation={[0.006, -0.3, 0.085]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder006_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[-1.626, 1.677, -2.1]}
        rotation={[0.009, 0.841, 0.077]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder007_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[-1.04, 1.776, -2.682]}
        rotation={[0.008, 0.683, 0.078]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder008_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[-2.146, 1.527, -1.447]}
        rotation={[0.187, 1.007, 0.038]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder009_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[2.398, 1.978, -0.775]}
        rotation={[0.31, -1.209, 0.154]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder010_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <group
        position={[2.54, 1.873, -0.067]}
        rotation={[1.617, -1.489, 1.467]}
        scale={[-0.018, -0.116, -0.018]}
      >
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011.geometry}
          material={materials["Fence Wood"]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Cylinder011_1.geometry}
          material={materials["Fence Top"]}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal.geometry}
        material={materials.Crystal}
        position={[0.225, -4.471, -0.458]}
        rotation={[0.069, 0.229, 0.155]}
        scale={[0.27, 0.731, 0.27]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal001.geometry}
        material={materials.Crystal}
        position={[0.105, -3.992, -0.783]}
        rotation={[-0.035, -0.03, -0.071]}
        scale={[0.188, 0.509, 0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal002.geometry}
        material={materials.Crystal}
        position={[-0.312, -4.916, -0.007]}
        rotation={[3.092, 0.865, -3.065]}
        scale={[0.221, 0.763, 0.221]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal003.geometry}
        material={materials.Crystal}
        position={[-0.458, -4.44, 0.235]}
        rotation={[-3.084, 0.926, 3.026]}
        scale={[0.154, 0.416, 0.154]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal004.geometry}
        material={materials.Crystal}
        position={[-0.76, -3.992, -0.783]}
        rotation={[-0.043, 0.641, -0.044]}
        scale={[0.188, 0.509, 0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal005.geometry}
        material={materials.Crystal}
        position={[-0.787, -4.16, 0.104]}
        rotation={[Math.PI, -1.129, Math.PI]}
        scale={[0.19, 0.656, 0.19]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal006.geometry}
        material={materials.Crystal}
        position={[-0.545, -3.902, 0.125]}
        rotation={[-3.065, -1.097, 3.14]}
        scale={[0.132, 0.358, 0.132]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal007.geometry}
        material={materials.Crystal}
        position={[-0.912, -4.493, -0.374]}
        rotation={[0, 0.232, 0]}
        scale={[0.156, 0.421, 0.156]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal008.geometry}
        material={materials.Crystal}
        position={[-1.023, -4.132, -0.54]}
        rotation={[-0.035, 0.202, -0.063]}
        scale={[0.108, 0.373, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal009.geometry}
        material={materials.Crystal}
        position={[-0.284, -3.902, -0.425]}
        rotation={[-0.174, -1.369, -0.241]}
        scale={[0.132, 0.358, 0.132]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal010.geometry}
        material={materials.Crystal}
        position={[1.22, -3.374, -0.26]}
        rotation={[0.039, -0.052, -0.118]}
        scale={[0.189, 0.926, 0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal011.geometry}
        material={materials.Crystal}
        position={[0.803, -4.905, 0.515]}
        rotation={[-3.068, 0.933, 3.034]}
        scale={[0.221, 1.092, 0.221]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal012.geometry}
        material={materials.Crystal}
        position={[0.202, -4.287, 0.149]}
        rotation={[-0.024, 0.196, 0.061]}
        scale={[0.156, 0.769, 0.156]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal013.geometry}
        material={materials.Crystal}
        position={[0.092, -3.784, -0.017]}
        rotation={[-0.035, 0.202, -0.063]}
        scale={[0.109, 0.534, 0.108]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal014.geometry}
        material={materials.Crystal}
        position={[1.231, -3.077, 0.483]}
        rotation={[-0.017, -0.035, 0.089]}
        scale={[0.189, 0.926, 0.188]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal015.geometry}
        material={materials.Crystal}
        position={[-0.733, -3.594, 0.865]}
        rotation={[3.074, -0.114, -2.979]}
        scale={[0.207, 0.559, 0.207]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Crystal016.geometry}
        material={materials.Crystal}
        position={[-0.147, -4.039, 0.48]}
        rotation={[0.058, -0.981, 0.087]}
        scale={[0.221, 0.763, 0.221]}
      />
    </group>
  );
}

useGLTF.preload("/assets/model.glb");